apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: qdr-operator
  namespace: openshift-marketplace
spec:
  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: interconnectedcloud
  displayName: "Qdr Operators"
  publisher: "Red Hat"
